// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluaqiL3u0KdiAxpcZYTVpupknaj3Zqps',
    appId: '1:121543407737:web:4bd2a8fa515662425b3ca8',
    messagingSenderId: '121543407737',
    projectId: 'custom-fit-37567',
    authDomain: 'custom-fit-37567.firebaseapp.com',
    storageBucket: 'custom-fit-37567.appspot.com',
    measurementId: 'G-7XGM3C0TWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQA-yOmAlsMpn5XUJCDvFL56ZP9lfs0zM',
    appId: '1:121543407737:android:bd39140a0a404ef05b3ca8',
    messagingSenderId: '121543407737',
    projectId: 'custom-fit-37567',
    storageBucket: 'custom-fit-37567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Li4f4zzaE0sZ7PRGAtRlwh7Mz_VqyQo',
    appId: '1:121543407737:ios:dcc063278eb8b1e95b3ca8',
    messagingSenderId: '121543407737',
    projectId: 'custom-fit-37567',
    storageBucket: 'custom-fit-37567.appspot.com',
    iosBundleId: 'com.example.customFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Li4f4zzaE0sZ7PRGAtRlwh7Mz_VqyQo',
    appId: '1:121543407737:ios:7f668f129499fc455b3ca8',
    messagingSenderId: '121543407737',
    projectId: 'custom-fit-37567',
    storageBucket: 'custom-fit-37567.appspot.com',
    iosBundleId: 'com.example.customFit.RunnerTests',
  );
}
